### ISSUE TITLE
Question: graduated style's name

### ISSUE THREAD

**Issue by pomeloEater** [NationalSecurityAgency/qgis-densityanalysis-plugin#2]
https://github.com/NationalSecurityAgency/qgis-densityanalysis-plugin/blob/a00e559455b5c475b209bc2982f8313212e6487b/graduatedstyle.py#L134

The file is named 'graduatedstyle.py', but has a name that the name function returns as 'gratuatedstyle'.
Is there a reason why the filename and the name function's return value are different?

**Comment by hamiltoncj** [comment]
Oops! I will fix that.

**Comment by hamiltoncj** [comment]
This has been completed. Thank you for catching the typo.
